name: Update Activity Gist

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Gist
      run: |
        curl -X PATCH "https://api.github.com/gists/${{ secrets.GIST_ID }}" \
        -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -d '{
          "files": {
            "activity.txt": {
              "content": "New activity content"
            }
          }
        }'

      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GIST_ID: ${{ secrets.GIST_ID }}
