name: Activity Gist

on:
  schedule:
    - cron: '*/15 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: JasonEtco/activity-box@master
    - name: Checkout
      uses: actions/checkout@v3
      
      env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: dmitriy-belkin
          GIST_ID: 152f3f1c3e0adeea56c01e56c3595021
