name: Update Gist with Activity

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch recent activity
        id: get_activity
        run: |
          RECENT_ACTIVITY=$(curl -s "https://api.github.com/users/dmitriy-belkin/events/public" | jq '.[0] | {created_at, type}')
          echo "activity=$RECENT_ACTIVITY" >> $GITHUB_ENV

      - name: Update Gist
        uses: peterevans/create-or-update-gist@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gist_id: e010e854bb5dec610d0ed1eefeaa83ea
          filename: activity.md
          content: "${{ env.activity }}"
