name: Activity Gist

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Environment Variables
        run: |
          echo "GH_PAT: ${{ secrets.GH_TOKEN }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "GH_USERNAME: dmitriy-belkin"
          echo "GIST_ID: e010e854bb5dec610d0ed1eefeaa83ea"

      - name: Fetch Recent Activity
        id: fetch_activity
        run: |
          RECENT_ACTIVITY=$(curl -s "https://api.github.com/users/dmitriy-belkin/events/public" | jq -r '.[0] | {created_at, type}')
          echo "RECENT_ACTIVITY=$RECENT_ACTIVITY" >> $GITHUB_ENV

      - name: Run Activity Box
        uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: dmitriy-belkin
          GIST_ID: e010e854bb5dec610d0ed1eefeaa83ea
