name: Activity Gist

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

    - uses: JasonEtco/activity-box@master
      env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: dmitriy-belkin
          GIST_ID: a40e6eaaf6e7ef5ea8afc45b65b7cb7d
