name: Time Gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 200b8f1d25f5bc5c49126e368ea2c9be
          TIMEZONE: Europe/Moscow